// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: menu.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MenuItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MenuItem) Reset() {
	*x = MenuItem{}
	mi := &file_menu_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MenuItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MenuItem) ProtoMessage() {}

func (x *MenuItem) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MenuItem.ProtoReflect.Descriptor instead.
func (*MenuItem) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{0}
}

func (x *MenuItem) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MenuItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MenuItem) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *MenuItem) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *MenuItem) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *MenuItem) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *MenuItem) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type CreateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,4,opt,name=available,proto3" json:"available,omitempty"`
	Category      string                 `protobuf:"bytes,5,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,6,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuItemRequest) Reset() {
	*x = CreateMenuItemRequest{}
	mi := &file_menu_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemRequest) ProtoMessage() {}

func (x *CreateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*CreateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{1}
}

func (x *CreateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateMenuItemRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *CreateMenuItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *CreateMenuItemRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type CreateMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateMenuItemResponse) Reset() {
	*x = CreateMenuItemResponse{}
	mi := &file_menu_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateMenuItemResponse) ProtoMessage() {}

func (x *CreateMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateMenuItemResponse.ProtoReflect.Descriptor instead.
func (*CreateMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{2}
}

func (x *CreateMenuItemResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMenuItemByIDRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemByIDRequest) Reset() {
	*x = GetMenuItemByIDRequest{}
	mi := &file_menu_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemByIDRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemByIDRequest) ProtoMessage() {}

func (x *GetMenuItemByIDRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemByIDRequest.ProtoReflect.Descriptor instead.
func (*GetMenuItemByIDRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{3}
}

func (x *GetMenuItemByIDRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type GetMenuItemByIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Item          *MenuItem              `protobuf:"bytes,1,opt,name=item,proto3" json:"item,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMenuItemByIDResponse) Reset() {
	*x = GetMenuItemByIDResponse{}
	mi := &file_menu_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMenuItemByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMenuItemByIDResponse) ProtoMessage() {}

func (x *GetMenuItemByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMenuItemByIDResponse.ProtoReflect.Descriptor instead.
func (*GetMenuItemByIDResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{4}
}

func (x *GetMenuItemByIDResponse) GetItem() *MenuItem {
	if x != nil {
		return x.Item
	}
	return nil
}

type UpdateMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price         float64                `protobuf:"fixed64,4,opt,name=price,proto3" json:"price,omitempty"`
	Available     bool                   `protobuf:"varint,5,opt,name=available,proto3" json:"available,omitempty"`
	Category      string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	ImageUrl      string                 `protobuf:"bytes,7,opt,name=image_url,json=imageUrl,proto3" json:"image_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemRequest) Reset() {
	*x = UpdateMenuItemRequest{}
	mi := &file_menu_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemRequest) ProtoMessage() {}

func (x *UpdateMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemRequest.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{5}
}

func (x *UpdateMenuItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *UpdateMenuItemRequest) GetAvailable() bool {
	if x != nil {
		return x.Available
	}
	return false
}

func (x *UpdateMenuItemRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *UpdateMenuItemRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type UpdateMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateMenuItemResponse) Reset() {
	*x = UpdateMenuItemResponse{}
	mi := &file_menu_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateMenuItemResponse) ProtoMessage() {}

func (x *UpdateMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateMenuItemResponse.ProtoReflect.Descriptor instead.
func (*UpdateMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateMenuItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type DeleteMenuItemRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuItemRequest) Reset() {
	*x = DeleteMenuItemRequest{}
	mi := &file_menu_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuItemRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemRequest) ProtoMessage() {}

func (x *DeleteMenuItemRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemRequest.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteMenuItemRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type DeleteMenuItemResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteMenuItemResponse) Reset() {
	*x = DeleteMenuItemResponse{}
	mi := &file_menu_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteMenuItemResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteMenuItemResponse) ProtoMessage() {}

func (x *DeleteMenuItemResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteMenuItemResponse.ProtoReflect.Descriptor instead.
func (*DeleteMenuItemResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{8}
}

func (x *DeleteMenuItemResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ListMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int64                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Skip          int64                  `protobuf:"varint,2,opt,name=skip,proto3" json:"skip,omitempty"`
	Search        string                 `protobuf:"bytes,3,opt,name=search,proto3" json:"search,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	SortBy        string                 `protobuf:"bytes,5,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	SortAsc       bool                   `protobuf:"varint,6,opt,name=sort_asc,json=sortAsc,proto3" json:"sort_asc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuItemsRequest) Reset() {
	*x = ListMenuItemsRequest{}
	mi := &file_menu_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuItemsRequest) ProtoMessage() {}

func (x *ListMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*ListMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{9}
}

func (x *ListMenuItemsRequest) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListMenuItemsRequest) GetSkip() int64 {
	if x != nil {
		return x.Skip
	}
	return 0
}

func (x *ListMenuItemsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListMenuItemsRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *ListMenuItemsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

func (x *ListMenuItemsRequest) GetSortAsc() bool {
	if x != nil {
		return x.SortAsc
	}
	return false
}

type ListMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	TotalCount    int64                  `protobuf:"varint,2,opt,name=total_count,json=totalCount,proto3" json:"total_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListMenuItemsResponse) Reset() {
	*x = ListMenuItemsResponse{}
	mi := &file_menu_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListMenuItemsResponse) ProtoMessage() {}

func (x *ListMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*ListMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{10}
}

func (x *ListMenuItemsResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListMenuItemsResponse) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

type GetMultipleMenuItemsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ids           []string               `protobuf:"bytes,1,rep,name=ids,proto3" json:"ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleMenuItemsRequest) Reset() {
	*x = GetMultipleMenuItemsRequest{}
	mi := &file_menu_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleMenuItemsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleMenuItemsRequest) ProtoMessage() {}

func (x *GetMultipleMenuItemsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleMenuItemsRequest.ProtoReflect.Descriptor instead.
func (*GetMultipleMenuItemsRequest) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{11}
}

func (x *GetMultipleMenuItemsRequest) GetIds() []string {
	if x != nil {
		return x.Ids
	}
	return nil
}

type GetMultipleMenuItemsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*MenuItem            `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetMultipleMenuItemsResponse) Reset() {
	*x = GetMultipleMenuItemsResponse{}
	mi := &file_menu_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetMultipleMenuItemsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetMultipleMenuItemsResponse) ProtoMessage() {}

func (x *GetMultipleMenuItemsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_menu_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetMultipleMenuItemsResponse.ProtoReflect.Descriptor instead.
func (*GetMultipleMenuItemsResponse) Descriptor() ([]byte, []int) {
	return file_menu_proto_rawDescGZIP(), []int{12}
}

func (x *GetMultipleMenuItemsResponse) GetItems() []*MenuItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_menu_proto protoreflect.FileDescriptor

const file_menu_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"menu.proto\x12\x04menu\"\xbd\x01\n" +
	"\bMenuItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\"\xba\x01\n" +
	"\x15CreateMenuItemRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x04 \x01(\bR\tavailable\x12\x1a\n" +
	"\bcategory\x18\x05 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\x06 \x01(\tR\bimageUrl\"(\n" +
	"\x16CreateMenuItemResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"(\n" +
	"\x16GetMenuItemByIDRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x17GetMenuItemByIDResponse\x12\"\n" +
	"\x04item\x18\x01 \x01(\v2\x0e.menu.MenuItemR\x04item\"\xca\x01\n" +
	"\x15UpdateMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05price\x18\x04 \x01(\x01R\x05price\x12\x1c\n" +
	"\tavailable\x18\x05 \x01(\bR\tavailable\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\x12\x1b\n" +
	"\timage_url\x18\a \x01(\tR\bimageUrl\"2\n" +
	"\x16UpdateMenuItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"'\n" +
	"\x15DeleteMenuItemRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"2\n" +
	"\x16DeleteMenuItemResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\xa8\x01\n" +
	"\x14ListMenuItemsRequest\x12\x14\n" +
	"\x05limit\x18\x01 \x01(\x03R\x05limit\x12\x12\n" +
	"\x04skip\x18\x02 \x01(\x03R\x04skip\x12\x16\n" +
	"\x06search\x18\x03 \x01(\tR\x06search\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\x12\x17\n" +
	"\asort_by\x18\x05 \x01(\tR\x06sortBy\x12\x19\n" +
	"\bsort_asc\x18\x06 \x01(\bR\asortAsc\"^\n" +
	"\x15ListMenuItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.menu.MenuItemR\x05items\x12\x1f\n" +
	"\vtotal_count\x18\x02 \x01(\x03R\n" +
	"totalCount\"/\n" +
	"\x1bGetMultipleMenuItemsRequest\x12\x10\n" +
	"\x03ids\x18\x01 \x03(\tR\x03ids\"D\n" +
	"\x1cGetMultipleMenuItemsResponse\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.menu.MenuItemR\x05items2\xed\x03\n" +
	"\vMenuService\x12K\n" +
	"\x0eCreateMenuItem\x12\x1b.menu.CreateMenuItemRequest\x1a\x1c.menu.CreateMenuItemResponse\x12N\n" +
	"\x0fGetMenuItemByID\x12\x1c.menu.GetMenuItemByIDRequest\x1a\x1d.menu.GetMenuItemByIDResponse\x12K\n" +
	"\x0eUpdateMenuItem\x12\x1b.menu.UpdateMenuItemRequest\x1a\x1c.menu.UpdateMenuItemResponse\x12K\n" +
	"\x0eDeleteMenuItem\x12\x1b.menu.DeleteMenuItemRequest\x1a\x1c.menu.DeleteMenuItemResponse\x12H\n" +
	"\rListMenuItems\x12\x1a.menu.ListMenuItemsRequest\x1a\x1b.menu.ListMenuItemsResponse\x12]\n" +
	"\x14GetMultipleMenuItems\x12!.menu.GetMultipleMenuItemsRequest\x1a\".menu.GetMultipleMenuItemsResponseB\x12Z\x10menu/proto;protob\x06proto3"

var (
	file_menu_proto_rawDescOnce sync.Once
	file_menu_proto_rawDescData []byte
)

func file_menu_proto_rawDescGZIP() []byte {
	file_menu_proto_rawDescOnce.Do(func() {
		file_menu_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)))
	})
	return file_menu_proto_rawDescData
}

var file_menu_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_menu_proto_goTypes = []any{
	(*MenuItem)(nil),                     // 0: menu.MenuItem
	(*CreateMenuItemRequest)(nil),        // 1: menu.CreateMenuItemRequest
	(*CreateMenuItemResponse)(nil),       // 2: menu.CreateMenuItemResponse
	(*GetMenuItemByIDRequest)(nil),       // 3: menu.GetMenuItemByIDRequest
	(*GetMenuItemByIDResponse)(nil),      // 4: menu.GetMenuItemByIDResponse
	(*UpdateMenuItemRequest)(nil),        // 5: menu.UpdateMenuItemRequest
	(*UpdateMenuItemResponse)(nil),       // 6: menu.UpdateMenuItemResponse
	(*DeleteMenuItemRequest)(nil),        // 7: menu.DeleteMenuItemRequest
	(*DeleteMenuItemResponse)(nil),       // 8: menu.DeleteMenuItemResponse
	(*ListMenuItemsRequest)(nil),         // 9: menu.ListMenuItemsRequest
	(*ListMenuItemsResponse)(nil),        // 10: menu.ListMenuItemsResponse
	(*GetMultipleMenuItemsRequest)(nil),  // 11: menu.GetMultipleMenuItemsRequest
	(*GetMultipleMenuItemsResponse)(nil), // 12: menu.GetMultipleMenuItemsResponse
}
var file_menu_proto_depIdxs = []int32{
	0,  // 0: menu.GetMenuItemByIDResponse.item:type_name -> menu.MenuItem
	0,  // 1: menu.ListMenuItemsResponse.items:type_name -> menu.MenuItem
	0,  // 2: menu.GetMultipleMenuItemsResponse.items:type_name -> menu.MenuItem
	1,  // 3: menu.MenuService.CreateMenuItem:input_type -> menu.CreateMenuItemRequest
	3,  // 4: menu.MenuService.GetMenuItemByID:input_type -> menu.GetMenuItemByIDRequest
	5,  // 5: menu.MenuService.UpdateMenuItem:input_type -> menu.UpdateMenuItemRequest
	7,  // 6: menu.MenuService.DeleteMenuItem:input_type -> menu.DeleteMenuItemRequest
	9,  // 7: menu.MenuService.ListMenuItems:input_type -> menu.ListMenuItemsRequest
	11, // 8: menu.MenuService.GetMultipleMenuItems:input_type -> menu.GetMultipleMenuItemsRequest
	2,  // 9: menu.MenuService.CreateMenuItem:output_type -> menu.CreateMenuItemResponse
	4,  // 10: menu.MenuService.GetMenuItemByID:output_type -> menu.GetMenuItemByIDResponse
	6,  // 11: menu.MenuService.UpdateMenuItem:output_type -> menu.UpdateMenuItemResponse
	8,  // 12: menu.MenuService.DeleteMenuItem:output_type -> menu.DeleteMenuItemResponse
	10, // 13: menu.MenuService.ListMenuItems:output_type -> menu.ListMenuItemsResponse
	12, // 14: menu.MenuService.GetMultipleMenuItems:output_type -> menu.GetMultipleMenuItemsResponse
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_menu_proto_init() }
func file_menu_proto_init() {
	if File_menu_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_menu_proto_rawDesc), len(file_menu_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_menu_proto_goTypes,
		DependencyIndexes: file_menu_proto_depIdxs,
		MessageInfos:      file_menu_proto_msgTypes,
	}.Build()
	File_menu_proto = out.File
	file_menu_proto_goTypes = nil
	file_menu_proto_depIdxs = nil
}
